FROM openjdk:8-jdk-alpine
#VOLUME /tmp
MAINTAINER Prukky
COPY config /config
COPY src/main/webapp /src/main/webapp
COPY src/main/resources /src/main/resources
COPY target/api-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
#EXPOSE 5557 45001 27301